;             
CREATE USER IF NOT EXISTS "SA" SALT '7d22a659f8a41087' HASH '06a2d29725bcf6950ce62502e62e53b3224453b233c68835a6919768f18246c8' ADMIN;         
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9298231B_E7C1_4CE7_BB48_B3F0876563E4" START WITH 3 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6E592E07_824C_4DFD_BD8E_24FFD607E07B" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_37A2426D_7573_4F25_A287_2E55A7119345" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6908C3C4_A4D8_45B8_8DDB_73BB586BAA22" START WITH 7 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CCCB7AED_9E99_48DE_B83A_E57F41493E1C" START WITH 8 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B096094A_2987_478D_8003_86331AF15B6B" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_63550E31_9094_42F8_8BBE_98617DBD79A1" START WITH 2 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F282C155_AF28_450F_BEC9_16AE4F8C768B" START WITH 9 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9817D50F_861E_4316_89C8_D645A200EB58" START WITH 6 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DDD7906E_8192_496E_8696_7352130E5A35" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DA46E7D5_F145_40C0_B9A2_EBA1C5C2A03F" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F5A50AB7_0C41_4911_9794_907DAE37B784" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0A26C769_4FE9_4C26_BDD6_7BE4F1BD34BD" START WITH 19 BELONGS_TO_TABLE;               
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_23BBFD1F_9FE7_40FC_8FC4_4814976D1E0E" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_10BF2FEC_A555_4C21_89F3_172C372C20F6" START WITH 5 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_07B792CF_5698_4B05_9EA6_3AD9102C0209" START WITH 6 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1D3A8468_2A8A_48AF_82F8_16DBD9EF5FB6" START WITH 9 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."ADHESION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DA46E7D5_F145_40C0_B9A2_EBA1C5C2A03F" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DA46E7D5_F145_40C0_B9A2_EBA1C5C2A03F",
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "PERSONNE_ID" BIGINT NOT NULL
);             
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");     
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADHESION;
CREATE MEMORY TABLE "PUBLIC"."CONTACT_PROFESSIONNEL"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_6E592E07_824C_4DFD_BD8E_24FFD607E07B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6E592E07_824C_4DFD_BD8E_24FFD607E07B",
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "CONTACT_ID" BIGINT NOT NULL
); 
ALTER TABLE "PUBLIC"."CONTACT_PROFESSIONNEL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONTACT_PROFESSIONNEL;   
CREATE MEMORY TABLE "PUBLIC"."DON"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_B096094A_2987_478D_8003_86331AF15B6B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B096094A_2987_478D_8003_86331AF15B6B",
    "DATE" DATE NOT NULL,
    "DESCRIPTION" VARCHAR(100),
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "PERSONNE_ID" BIGINT NOT NULL,
    "STATUT_ID" BIGINT NOT NULL,
    "TYPE_DON_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("ID");          
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DON;     
CREATE MEMORY TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_DDD7906E_8192_496E_8696_7352130E5A35" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_DDD7906E_8192_496E_8696_7352130E5A35",
    "URL" VARCHAR(250) NOT NULL,
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "RESEAU_SOCIAL_ID" BIGINT NOT NULL
);            
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");           
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LIEN_RESEAU_SOCIAL;      
CREATE MEMORY TABLE "PUBLIC"."ADRESSE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_0A26C769_4FE9_4C26_BDD6_7BE4F1BD34BD" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_0A26C769_4FE9_4C26_BDD6_7BE4F1BD34BD",
    "CODE_POSTAL" VARCHAR(20) NOT NULL,
    "COMPLEMENT" VARCHAR(100),
    "RUE" VARCHAR(250) NOT NULL,
    "VILLE" VARCHAR(250) NOT NULL
);          
ALTER TABLE "PUBLIC"."ADRESSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E7" PRIMARY KEY("ID");     
-- 17 +/- SELECT COUNT(*) FROM PUBLIC.ADRESSE;
INSERT INTO "PUBLIC"."ADRESSE" VALUES
(1, '22100', NULL, '58 Rue de l''Apport', 'Dinan'),
(2, '22100', NULL, '9 Rue de Lehon', 'Dinan'),
(3, '22100', NULL, '14 Rue de La Poissonnerie', 'Dinan'),
(4, '25300', 'Centre Commercial Hyper U', STRINGDECODE('2 Rue de Besan\u00e7on'), 'Doubs'),
(5, '25300', NULL, '3 Rue du Bois de L''Oie', STRINGDECODE('Ar\u00e7on')),
(6, '25300', NULL, '23 Grande Rue', 'Doubs'),
(7, '08200', NULL, '7 Rue Thiers', 'Sedan'),
(8, '08200', NULL, STRINGDECODE('4 Promenoir des Pr\u00eatres'), 'Sedan'),
(9, '08200', NULL, '2 Rue Renan', 'Doubs'),
(10, '22100', NULL, '58 Rue de l''Apport', 'Dinan'),
(11, '22100', NULL, '9 Rue de Lehon', 'Dinan'),
(12, '22100', NULL, '14 Rue de La Poissonnerie', 'Dinan'),
(14, '25300', NULL, '3 Rue du Bois de L''Oie', STRINGDECODE('Ar\u00e7on')),
(15, '25300', NULL, '23 Grande Rue', 'Doubs'),
(16, '08200', NULL, '7 Rue Thiers', 'Sedan'),
(17, '08200', NULL, STRINGDECODE('4 Promenoir des Pr\u00eatres'), 'Sedan'),
(18, '08200', NULL, '2 Rue Renan', 'Doubs');
CREATE MEMORY TABLE "PUBLIC"."ASSOCIATION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_07B792CF_5698_4B05_9EA6_3AD9102C0209" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_07B792CF_5698_4B05_9EA6_3AD9102C0209",
    "MAIL" VARCHAR(100) NOT NULL,
    "NOM" VARCHAR(100) NOT NULL,
    "NUMRNA" VARCHAR(40) NOT NULL,
    "TELEPHONE" VARCHAR(20),
    "URL" VARCHAR(100),
    "ADRESSE_ID" BIGINT NOT NULL,
    "CATEGORIE_ID" BIGINT NOT NULL,
    "STATUT_ID" BIGINT NOT NULL
);           
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");  
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.ASSOCIATION;             
INSERT INTO "PUBLIC"."ASSOCIATION" VALUES
(1, 'contact@boulistes-sans-frontieres.fr', STRINGDECODE('Boulistes sans fronti\u00e8res'), 'W223344556', '06 29 15 08 15', NULL, 1, 2, 3),
(4, 'sport442@gmail.fr', 'Sport 442', 'W220442556', '06 39 15 08 15', 'http://sport-442.fr', 4, 2, 3);
CREATE MEMORY TABLE "PUBLIC"."CATEGORIE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_CCCB7AED_9E99_48DE_B83A_E57F41493E1C" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_CCCB7AED_9E99_48DE_B83A_E57F41493E1C",
    "NOM" VARCHAR(80) NOT NULL
);      
ALTER TABLE "PUBLIC"."CATEGORIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");    
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORIE;               
INSERT INTO "PUBLIC"."CATEGORIE" VALUES
(1, 'Humanitaire'),
(2, 'Sport'),
(3, STRINGDECODE('Charit\u00e9')),
(7, 'Loisir');               
CREATE MEMORY TABLE "PUBLIC"."MEDIA"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_23BBFD1F_9FE7_40FC_8FC4_4814976D1E0E" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_23BBFD1F_9FE7_40FC_8FC4_4814976D1E0E",
    "PATH" VARCHAR(100) NOT NULL,
    "TITRE" VARCHAR(100) NOT NULL,
    "URL" VARCHAR(100) NOT NULL,
    "ASSOCIATION_ID" BIGINT,
    "PERSONNE_ID" BIGINT
);         
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_45" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEDIA;   
CREATE MEMORY TABLE "PUBLIC"."OFFRE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_6908C3C4_A4D8_45B8_8DDB_73BB586BAA22" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_6908C3C4_A4D8_45B8_8DDB_73BB586BAA22",
    "DATE_DEBUT" DATE,
    "DATE_FIN" DATE,
    "ASSOCIATION_ID" BIGINT,
    "PROPOSITION_ID" BIGINT
); 
ALTER TABLE "PUBLIC"."OFFRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_47" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.OFFRE;   
INSERT INTO "PUBLIC"."OFFRE" VALUES
(4, DATE '2011-03-13', DATE '2018-02-11', 4, 3);         
CREATE MEMORY TABLE "PUBLIC"."PERSONNE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_37A2426D_7573_4F25_A287_2E55A7119345" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_37A2426D_7573_4F25_A287_2E55A7119345",
    "EMAIL" VARCHAR(200) NOT NULL,
    "LOGIN" VARCHAR(100) NOT NULL,
    "MOT_DE_PASSE" VARCHAR(255) NOT NULL,
    "NOM" VARCHAR(200) NOT NULL,
    "PRENOM" VARCHAR(100) NOT NULL,
    "ADRESSE_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL,
    "STATUT_ID" BIGINT NOT NULL
);         
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_49" PRIMARY KEY("ID");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PERSONNE;
CREATE MEMORY TABLE "PUBLIC"."PRESTATAIRE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F5A50AB7_0C41_4911_9794_907DAE37B784" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F5A50AB7_0C41_4911_9794_907DAE37B784",
    "EMAIL" VARCHAR(100) NOT NULL,
    "NOM" VARCHAR(100) NOT NULL,
    "ADRESSE_ID" BIGINT,
    "STATUT_ID" BIGINT NOT NULL
);   
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A" PRIMARY KEY("ID"); 
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRESTATAIRE;             
CREATE MEMORY TABLE "PUBLIC"."PROPOSITION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_9817D50F_861E_4316_89C8_D645A200EB58" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9817D50F_861E_4316_89C8_D645A200EB58",
    "NOM" VARCHAR(100) NOT NULL,
    "PRIX" DOUBLE NOT NULL,
    "TYPE_PROPOSITION_ID" BIGINT NOT NULL
);          
ALTER TABLE "PUBLIC"."PROPOSITION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E3" PRIMARY KEY("ID"); 
-- 5 +/- SELECT COUNT(*) FROM PUBLIC.PROPOSITION;             
INSERT INTO "PUBLIC"."PROPOSITION" VALUES
(1, 'Cours d''Anglais', 30.2, 1),
(2, 'Location Salle', 3000.0, 1),
(3, 'Location Stade', 50000.0, 1),
(4, STRINGDECODE('R\u00e9paration informatique'), 40.0, 1),
(5, 'Garde d''enfant', 3000.0, 1);          
CREATE MEMORY TABLE "PUBLIC"."RESEAU_SOCIAL"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_1D3A8468_2A8A_48AF_82F8_16DBD9EF5FB6" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_1D3A8468_2A8A_48AF_82F8_16DBD9EF5FB6",
    "NOM" VARCHAR(100) NOT NULL
); 
ALTER TABLE "PUBLIC"."RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_ED" PRIMARY KEY("ID");               
-- 8 +/- SELECT COUNT(*) FROM PUBLIC.RESEAU_SOCIAL;           
INSERT INTO "PUBLIC"."RESEAU_SOCIAL" VALUES
(1, 'Youtube'),
(2, 'Tiktok'),
(3, 'Instagram'),
(4, 'Facebook'),
(5, 'Twitter'),
(6, 'Linkedin'),
(7, 'Tumblr'),
(8, 'Mastodon');        
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_10BF2FEC_A555_4C21_89F3_172C372C20F6" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_10BF2FEC_A555_4C21_89F3_172C372C20F6",
    "NOM" VARCHAR(50) NOT NULL
);           
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;    
INSERT INTO "PUBLIC"."ROLE" VALUES
(1, STRINGDECODE('Adh\u00e9rent')),
(2, 'Donateur'),
(3, 'Administrateur association'),
(4, STRINGDECODE('Administrateur syst\u00e8me'));              
CREATE MEMORY TABLE "PUBLIC"."TYPE_DON"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_9298231B_E7C1_4CE7_BB48_B3F0876563E4" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_9298231B_E7C1_4CE7_BB48_B3F0876563E4",
    "NOM" VARCHAR(20) NOT NULL
);       
ALTER TABLE "PUBLIC"."TYPE_DON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("ID");     
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.TYPE_DON;
INSERT INTO "PUBLIC"."TYPE_DON" VALUES
(1, 'Financier'),
(2, STRINGDECODE('Mat\u00e9riel'));
CREATE MEMORY TABLE "PUBLIC"."STATUT"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F282C155_AF28_450F_BEC9_16AE4F8C768B" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F282C155_AF28_450F_BEC9_16AE4F8C768B",
    "NOM" VARCHAR(40) NOT NULL
);         
ALTER TABLE "PUBLIC"."STATUT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");       
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.STATUT;  
INSERT INTO "PUBLIC"."STATUT" VALUES
(1, STRINGDECODE('Accept\u00e9')),
(2, STRINGDECODE('Refus\u00e9')),
(3, 'Actif'),
(4, 'Inactif');   
CREATE MEMORY TABLE "PUBLIC"."TYPE_PROPOSITION"(
    "ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_63550E31_9094_42F8_8BBE_98617DBD79A1" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_63550E31_9094_42F8_8BBE_98617DBD79A1",
    "NOM" VARCHAR(80) NOT NULL
);               
ALTER TABLE "PUBLIC"."TYPE_PROPOSITION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("ID");             
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TYPE_PROPOSITION;        
INSERT INTO "PUBLIC"."TYPE_PROPOSITION" VALUES
(1, 'Service');               
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."UK_8L3J8SMOM1KAPEU3Y4F4D6G3G" UNIQUE("LOGIN");       
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."UK_AV0QETEVAX86BF1WKMG2NB5K2" UNIQUE("URL");               
ALTER TABLE "PUBLIC"."RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."UK_LS1LGWPNI0GM0IU79K4B1TUSY" UNIQUE("NOM");    
ALTER TABLE "PUBLIC"."STATUT" ADD CONSTRAINT "PUBLIC"."UK_T5V7ON4J23MYDUUDG0OQ9Y47K" UNIQUE("NOM");           
ALTER TABLE "PUBLIC"."PROPOSITION" ADD CONSTRAINT "PUBLIC"."UK_T3APRH7EX8VBM8VOFHKTMNKN7" UNIQUE("NOM");      
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."UK_GP9BUE980TMA9YHT908N9ALEB" UNIQUE("URL");            
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."UK_6U1K6PQQ7SUWEPWCFSKYMPY3S" UNIQUE("NOM");             
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_BI61YIAN1LWRE9U9RLBAW4S63" UNIQUE("TELEPHONE");
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_OS6FD6HNG87K1I4IKJOJBX20J" UNIQUE("NUMRNA");   
ALTER TABLE "PUBLIC"."ADRESSE" ADD CONSTRAINT "PUBLIC"."UKBDGMC0S44MKI3ETGTJHRCK1FU" UNIQUE("RUE", "COMPLEMENT", "CODE_POSTAL", "VILLE");     
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."UK_EFCDXUJENO0GKQUU69EXNDDTO" UNIQUE("PATH");           
ALTER TABLE "PUBLIC"."CATEGORIE" ADD CONSTRAINT "PUBLIC"."UK_89Y3D23IA9RUHFHDMYA9ASPQ7" UNIQUE("NOM");        
ALTER TABLE "PUBLIC"."TYPE_PROPOSITION" ADD CONSTRAINT "PUBLIC"."UK_8HFT0CSJ94N3XQ5ORDPDE9US3" UNIQUE("NOM"); 
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_PK6QQF0X3MUHJ7Q5CXSRRRTQ1" UNIQUE("MAIL");     
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."UK_5Y3TRPPE86PSJ2VYW7334Y2XS" UNIQUE("TITRE");          
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_IYSSU3KV05DSMEQERC9YFORVJ" UNIQUE("NOM");      
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."UK_LIF11UG7PQKDIMUK0BEONBFNG" UNIQUE("EMAIL");       
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."UKTDKWUFYNBMKV2RM4DQXA21L2D" UNIQUE("ASSOCIATION_ID", "PERSONNE_ID");
ALTER TABLE "PUBLIC"."TYPE_DON" ADD CONSTRAINT "PUBLIC"."UK_1G00PHVK71Y9GHBK9CIPFM3S1" UNIQUE("NOM");         
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."UK_MVXFN94YTSR9QBISKRN6BHC86" UNIQUE("NOM");      
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."UK_BB7JAHRD8OM07KOARUO6S24GU" UNIQUE("EMAIL");    
ALTER TABLE "PUBLIC"."CONTACT_PROFESSIONNEL" ADD CONSTRAINT "PUBLIC"."FK91VBTWFPHCIBWH2FOQ5HDD5Y8" FOREIGN KEY("CONTACT_ID") REFERENCES "PUBLIC"."PRESTATAIRE"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."OFFRE" ADD CONSTRAINT "PUBLIC"."FK7D2UJE6PIPXWJFXAYPIQ08WDR" FOREIGN KEY("PROPOSITION_ID") REFERENCES "PUBLIC"."PROPOSITION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."PROPOSITION" ADD CONSTRAINT "PUBLIC"."FKQYI8P258GA7RRWSTE8OY84NOI" FOREIGN KEY("TYPE_PROPOSITION_ID") REFERENCES "PUBLIC"."TYPE_PROPOSITION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."FKL90JW5NSTABN1D86OT671VDG0" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."CONTACT_PROFESSIONNEL" ADD CONSTRAINT "PUBLIC"."FKDTW5MY6BDYS9DBH03QJ9NOT2N" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."OFFRE" ADD CONSTRAINT "PUBLIC"."FKIWCH92SVCHHTO5WOUEDHJHBMW" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."FKJECJ1A4KAJ1Q22T2BDRF74GF3" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ID") NOCHECK;        
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."FK6VXV0B1D377PNHMTBD5T1MTUE" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FK8KEPX3FVJG51KQCIR9Q9NJ4HX" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."FKNG84MJK8470YNR5TGITGAFL5E" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ID") NOCHECK;             
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."FK47VWC3EXI8YC0PHF8J6UPHG4D" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("ID") NOCHECK;    
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."FKRMS58XF4N4371DCJJQL25JHE5" FOREIGN KEY("CATEGORIE_ID") REFERENCES "PUBLIC"."CATEGORIE"("ID") NOCHECK;           
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."FKDI7Y7UJ3OFK2FVNYCTYOINWOT" FOREIGN KEY("RESEAU_SOCIAL_ID") REFERENCES "PUBLIC"."RESEAU_SOCIAL"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."FK5PELR55TSIONMLT62J7SAPOJ8" FOREIGN KEY("PERSONNE_ID") REFERENCES "PUBLIC"."PERSONNE"("ID") NOCHECK;   
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."FKI7UAPYSGUM1TBKYWD9SL6VGFV" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("ID") NOCHECK; 
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FK7XQQSY58Y0G2JBRI4KAKJ634O" FOREIGN KEY("PERSONNE_ID") REFERENCES "PUBLIC"."PERSONNE"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FK1YQLASBF9RAJ5ERY94QR9MDG7" FOREIGN KEY("TYPE_DON_ID") REFERENCES "PUBLIC"."TYPE_DON"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."FKBQYP50TPTM2IR85AI8UEAHW7O" FOREIGN KEY("ADRESSE_ID") REFERENCES "PUBLIC"."ADRESSE"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."FKNJPH05DTGEG5OB8V0JV0VX0FH" FOREIGN KEY("ADRESSE_ID") REFERENCES "PUBLIC"."ADRESSE"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."FK64WYPB6GO3KIEGRP8NTDF7YWP" FOREIGN KEY("ADRESSE_ID") REFERENCES "PUBLIC"."ADRESSE"("ID") NOCHECK;  
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."FKHRDO8LX016DN1A3OT095JO964" FOREIGN KEY("PERSONNE_ID") REFERENCES "PUBLIC"."PERSONNE"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FKCOBXNQ6LQ8UAMG6F3PSJWEUR3" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."FKH0KBBW8UY35E2XPTHHUGA8MY7" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ID") NOCHECK;
