INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('58 Rue de l''Apport', 'Dinan' , '22100', null);
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('9 Rue de Lehon', 'Dinan' , '22100', null);
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('14 Rue de La Poissonnerie', 'Dinan' , '22100', null);
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('2 Rue de Besançon', 'Doubs' , '25300', 'Centre Commercial Hyper U');
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('3 Rue du Bois de L''Oie', 'Arçon' , '25300', null);
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('23 Grande Rue', 'Doubs' , '25300', null);
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('7 Rue Thiers', 'Sedan' , '08200', null);
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('4 Promenoir des Prêtres', 'Sedan' , '08200', null);
INSERT INTO ADRESSE (RUE, VILLE, CODE_POSTAL, COMPLEMENT) VALUES ('2 Rue Renan', 'Doubs' , '08200', null);

INSERT INTO CATEGORIE (NOM) VALUES ('Humanitaire');
INSERT INTO CATEGORIE (NOM) VALUES ('Sport');
INSERT INTO CATEGORIE (NOM) VALUES ('Charité');
INSERT INTO CATEGORIE (NOM) VALUES ('Loisir');

INSERT INTO TYPE_DON (NOM) VALUES ('Financier');
INSERT INTO TYPE_DON (NOM) VALUES ('Matériel');

INSERT INTO TYPE_PROPOSITION (NOM) VALUES ('Service');

INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Youtube');
INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Tiktok');
INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Instagram');
INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Facebook');
INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Twitter');
INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Linkedin');
INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Tumblr');
INSERT INTO RESEAU_SOCIAL (NOM) VALUES ('Mastodon');

INSERT INTO STATUT (NOM) VALUES ('Accepté');
INSERT INTO STATUT (NOM) VALUES ('Refusé');
INSERT INTO STATUT (NOM) VALUES ('Actif');
INSERT INTO STATUT (NOM) VALUES ('Inactif');

INSERT INTO ROLE (NOM) VALUES ('Adhérent');
INSERT INTO ROLE (NOM) VALUES ('Donateur');
INSERT INTO ROLE (NOM) VALUES ('Administrateur association');
INSERT INTO ROLE (NOM) VALUES ('Administrateur système');

INSERT INTO ASSOCIATION (NOM, NUMRNA, MAIL, TELEPHONE, URL, ADRESSE_ID, CATEGORIE_ID, STATUT_ID) VALUES ('Boulistes sans frontières', 'W223344556', 'contact@boulistes-sans-frontieres.fr', '06 29 15 08 15', null, 1, 2, 3);
INSERT INTO ASSOCIATION (NOM, NUMRNA, MAIL, TELEPHONE, URL, ADRESSE_ID, CATEGORIE_ID, STATUT_ID) VALUES ('Video-Klub', 'W223354956', 'video-klub@caramail.fr', '06 09 15 08 15', null, 2, 4, 3);
INSERT INTO ASSOCIATION (NOM, NUMRNA, MAIL, TELEPHONE, URL, ADRESSE_ID, CATEGORIE_ID, STATUT_ID) VALUES ('Fourneaux-Coopérative', 'W123354556', 'fourneaux-coop@gmail.fr', '06 09 15 18 15', null, 3, 4, 3);
INSERT INTO ASSOCIATION (NOM, NUMRNA, MAIL, TELEPHONE, URL, ADRESSE_ID, CATEGORIE_ID, STATUT_ID) VALUES ('Sport 442', 'W220442556', 'sport442@gmail.fr', '06 39 15 08 15', 'http://sport-442.fr', 4, 2, 3);
INSERT INTO ASSOCIATION (NOM, NUMRNA, MAIL, TELEPHONE, URL, ADRESSE_ID, CATEGORIE_ID, STATUT_ID) VALUES ('Mille livres', 'W220442557', 'livres1000@lycos.fr', '06 39 15 48 15', 'http://1000-livres.fr', 5, 4, 3);

INSERT INTO PROPOSITION (NOM, PRIX, TYPE_PROPOSITION_ID) VALUES ('Cours d''Anglais', 30.20, 1);
INSERT INTO PROPOSITION (NOM, PRIX, TYPE_PROPOSITION_ID) VALUES ('Location Salle', 3000, 1);
INSERT INTO PROPOSITION (NOM, PRIX, TYPE_PROPOSITION_ID) VALUES ('Location Stade', 50000, 1);
INSERT INTO PROPOSITION (NOM, PRIX, TYPE_PROPOSITION_ID) VALUES ('Réparation informatique', 40, 1);
INSERT INTO PROPOSITION (NOM, PRIX, TYPE_PROPOSITION_ID) VALUES ('Garde d''enfant', 3000, 1);

INSERT INTO OFFRE (DATE_DEBUT, DATE_FIN, ASSOCIATION_ID, PROPOSITION_ID) VALUES ('2023-01-12', '2023-03-04', 5, 1);
INSERT INTO OFFRE (DATE_DEBUT, DATE_FIN, ASSOCIATION_ID, PROPOSITION_ID) VALUES ('2022-07-05', '2025-03-02', 2, 2);
INSERT INTO OFFRE (DATE_DEBUT, DATE_FIN, ASSOCIATION_ID, PROPOSITION_ID) VALUES ('2012-08-22', '2023-04-01', 3, 2);
INSERT INTO OFFRE (DATE_DEBUT, DATE_FIN, ASSOCIATION_ID, PROPOSITION_ID) VALUES ('2011-03-13', '2018-02-11', 4, 3);
INSERT INTO OFFRE (DATE_DEBUT, DATE_FIN, ASSOCIATION_ID, PROPOSITION_ID) VALUES ('2020-06-06', '2025-01-14', 5, 4);
INSERT INTO OFFRE (DATE_DEBUT, DATE_FIN, ASSOCIATION_ID, PROPOSITION_ID) VALUES ('2022-11-02', '2035-1-14', 5, 5);