INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('58', 'Rue de l\'Apport', 'Dinan' , '22100', null);
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('9', 'Rue de Lehon', 'Dinan' , '22100', null);
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('14', 'Rue de La Poissonnerie', 'Dinan' , '22100', null);
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('2', 'Rue de Besançon', 'Doubs' , '25300', 'Centre Commercial Hyper U');
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('3', 'Rue du Bois de L\'Oie', 'Arçon' , '25300', null);
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('23', 'Grande Rue', 'Doubs' , '25300', null);
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('7', 'Rue Thiers', 'Sedan' , '08200', null);
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('4', 'Promenoir des Prêtres', 'Sedan' , '08200', null);
INSERT INTO ADRESSE (ADRESSE_NUMERO, ADRESSE_RUE, ADRESSE_VILLE, ADRESSE_CODE_POSTAL, ADRESSE_COMPLEMENT) VALUES ('2', 'Rue Renan', 'Doubs' , '08200', null);

INSERT INTO CATEGORIE (CATEGORIE_NOM) VALUES ('Humanitaire');
INSERT INTO CATEGORIE (CATEGORIE_NOM) VALUES ('Sport');
INSERT INTO CATEGORIE (CATEGORIE_NOM) VALUES ('Charité');

INSERT INTO TYPE_DON (TYPE_DON_NOM) VALUES ('Financier');
INSERT INTO TYPE_DON (TYPE_DON_NOM) VALUES ('Matériel');

INSERT INTO TYPE_PROPOSITION (TYPE_PROPOSITION_NOM) VALUES ('Service');