CREATE USER IF NOT EXISTS "SA" SALT '53e6809496b00a19' HASH 'c5a41359746706ea85ea150720dd9defd4faf2720f06fa43099d9b76e073a1bb' ADMIN;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F8366BE3_D8B3_42A0_A856_8A8737B77B0C" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AFD8181B_8DAB_4F2D_8869_69C38C7814CC" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_318D6FAA_A6F4_48A6_ACBA_1EED9D79EDE4" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_01BD89EE_9DAF_45D6_A1F2_4BA6ABD06446" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B4F49842_6689_42D8_8FB4_3540C6B19CB4" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_610ADA29_EC9F_404B_A225_487148827ADD" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2D2D0084_314C_4C43_BF08_B3F952A3B679" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_BB123BCF_19D3_446F_AC8C_1100C3400FCA" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_606C2CAF_870B_4C74_A40C_CC1EE9377ED9" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_68C70E90_EA11_45F4_9A00_CBFAF8F175AE" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F7A9416_6F22_4661_80E9_ABCA9EF21F1C" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E2EE5660_D755_458C_8AF6_76B1CA6684B5" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_81ACF5FC_A583_4111_B0DF_39CF58406387" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_24D606D4_2FCA_476B_8D2F_4AB973033310" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3BFBCB41_20E8_42F4_8AF4_6FE0AA2285F2" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_03D1C7AC_0F08_4A33_8133_E061E98C78EE" START WITH 1 BELONGS_TO_TABLE;
CREATE SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EA1053B1_6576_4DB2_9D88_56F0834BDE7D" START WITH 1 BELONGS_TO_TABLE;
CREATE MEMORY TABLE "PUBLIC"."ADHESION"(
    "ADHESION_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_5F7A9416_6F22_4661_80E9_ABCA9EF21F1C" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_5F7A9416_6F22_4661_80E9_ABCA9EF21F1C",
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "PERSONNE_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ADHESION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADHESION;
CREATE MEMORY TABLE "PUBLIC"."ADRESSE"(
    "ADRESSE_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_BB123BCF_19D3_446F_AC8C_1100C3400FCA" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_BB123BCF_19D3_446F_AC8C_1100C3400FCA",
    "ADRESSE_CODE_POSTAL" VARCHAR(20) NOT NULL,
    "ADRESSE_COMPLEMENT" VARCHAR(100) NOT NULL,
    "ADRESSE_NUMERO" VARCHAR(10) NOT NULL,
    "ADRESSE_RUE" VARCHAR(250) NOT NULL,
    "ADRESSE_VILLE" VARCHAR(250) NOT NULL
);
ALTER TABLE "PUBLIC"."ADRESSE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E7" PRIMARY KEY("ADRESSE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ADRESSE;
CREATE MEMORY TABLE "PUBLIC"."ASSOCIATION"(
    "ASSOCIATION_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_B4F49842_6689_42D8_8FB4_3540C6B19CB4" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_B4F49842_6689_42D8_8FB4_3540C6B19CB4",
    "ASSOCIATION_MAIL" VARCHAR(100) NOT NULL,
    "ASSOCIATION_NOM" VARCHAR(100) NOT NULL,
    "ASSOCIATION_NUMERO_RNA" VARCHAR(40) NOT NULL,
    "TELEPHONE" VARCHAR(20),
    "URL" VARCHAR(100),
    "ADRESSE_ID" BIGINT NOT NULL,
    "CATEGORIE_ID" BIGINT NOT NULL,
    "STATUT_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ASSOCIATION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ASSOCIATION;
CREATE MEMORY TABLE "PUBLIC"."CATEGORIE"(
    "CATEGORIE_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_F8366BE3_D8B3_42A0_A856_8A8737B77B0C" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_F8366BE3_D8B3_42A0_A856_8A8737B77B0C",
    "NOM" VARCHAR(80) NOT NULL
);
ALTER TABLE "PUBLIC"."CATEGORIE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("CATEGORIE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CATEGORIE;
CREATE MEMORY TABLE "PUBLIC"."CONTACT_PROFESSIONNEL"(
    "CONTACT_PROFESSIONNEL_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_2D2D0084_314C_4C43_BF08_B3F952A3B679" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_2D2D0084_314C_4C43_BF08_B3F952A3B679",
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "CONTACT_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."CONTACT_PROFESSIONNEL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("CONTACT_PROFESSIONNEL_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.CONTACT_PROFESSIONNEL;
CREATE MEMORY TABLE "PUBLIC"."DON"(
    "DON_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_610ADA29_EC9F_404B_A225_487148827ADD" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_610ADA29_EC9F_404B_A225_487148827ADD",
    "DON_DATE" DATE NOT NULL,
    "DON_DESCRIPTION" VARCHAR(100),
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "PERSONNE_ID" BIGINT NOT NULL,
    "STATUT_ID" BIGINT NOT NULL,
    "TYPE_DON_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_1" PRIMARY KEY("DON_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DON;
CREATE MEMORY TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL"(
    "LIEN_RESEAU_SOCIAL_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_606C2CAF_870B_4C74_A40C_CC1EE9377ED9" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_606C2CAF_870B_4C74_A40C_CC1EE9377ED9",
    "LIEN_RESEAU_SOCIAL_URL" VARCHAR(250) NOT NULL,
    "ASSOCIATION_ID" BIGINT NOT NULL,
    "RESEAU_SOCIAL_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("LIEN_RESEAU_SOCIAL_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.LIEN_RESEAU_SOCIAL;
CREATE MEMORY TABLE "PUBLIC"."MEDIA"(
    "MEDIA_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_AFD8181B_8DAB_4F2D_8869_69C38C7814CC" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_AFD8181B_8DAB_4F2D_8869_69C38C7814CC",
    "MEDIA_PATH" VARCHAR(100) NOT NULL,
    "MEDIA_TITRE" VARCHAR(100) NOT NULL,
    "MEDIA_URL" VARCHAR(100) NOT NULL,
    "ASSOCIATION_ID" BIGINT,
    "PERSONNE_ID" BIGINT
);
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_45" PRIMARY KEY("MEDIA_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.MEDIA;
CREATE MEMORY TABLE "PUBLIC"."OFFRE"(
    "OFFRE_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_E2EE5660_D755_458C_8AF6_76B1CA6684B5" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_E2EE5660_D755_458C_8AF6_76B1CA6684B5",
    "DATE_DEBUT" DATE,
    "DATE_FIN" DATE,
    "ASSOCIATION_ID" BIGINT,
    "PROPOSITION_ID" BIGINT
);
ALTER TABLE "PUBLIC"."OFFRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_47" PRIMARY KEY("OFFRE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.OFFRE;
CREATE MEMORY TABLE "PUBLIC"."PERSONNE"(
    "PERSONNE_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_01BD89EE_9DAF_45D6_A1F2_4BA6ABD06446" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_01BD89EE_9DAF_45D6_A1F2_4BA6ABD06446",
    "EMAIL" VARCHAR(200) NOT NULL,
    "PERSONNE_IDENTIFIANT" VARCHAR(100) NOT NULL,
    "PERSONNE_MOT_DE_PASSE" VARCHAR(255) NOT NULL,
    "PERSONNE_NOM" VARCHAR(200) NOT NULL,
    "PERSONNE_PRENOM" VARCHAR(100) NOT NULL,
    "ADRESSE_ID" BIGINT NOT NULL,
    "ROLE_ID" BIGINT NOT NULL,
    "STATUT_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_49" PRIMARY KEY("PERSONNE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PERSONNE;
CREATE MEMORY TABLE "PUBLIC"."PRESTATAIRE"(
    "PRESTATAIRE_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_68C70E90_EA11_45F4_9A00_CBFAF8F175AE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_68C70E90_EA11_45F4_9A00_CBFAF8F175AE",
    "PRESTATAIRE_EMAIL" VARCHAR(100) NOT NULL,
    "PRESTATAIRE_NOM" VARCHAR(100) NOT NULL,
    "ADRESSE_ID" BIGINT,
    "STATUT_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3A" PRIMARY KEY("PRESTATAIRE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PRESTATAIRE;
CREATE MEMORY TABLE "PUBLIC"."PROPOSITION"(
    "PROPOSITION_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_24D606D4_2FCA_476B_8D2F_4AB973033310" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_24D606D4_2FCA_476B_8D2F_4AB973033310",
    "PROPOSITION_NOM" VARCHAR(100) NOT NULL,
    "PRIX" DOUBLE NOT NULL,
    "TYPE_PROPOSITION_ID" BIGINT NOT NULL
);
ALTER TABLE "PUBLIC"."PROPOSITION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E3" PRIMARY KEY("PROPOSITION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PROPOSITION;
CREATE MEMORY TABLE "PUBLIC"."RESEAU_SOCIAL"(
    "RESEAU_SOCIAL_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_318D6FAA_A6F4_48A6_ACBA_1EED9D79EDE4" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_318D6FAA_A6F4_48A6_ACBA_1EED9D79EDE4",
    "RESEAU_SOCIAL_NOM" VARCHAR(100) NOT NULL
);
ALTER TABLE "PUBLIC"."RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_ED" PRIMARY KEY("RESEAU_SOCIAL_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.RESEAU_SOCIAL;
CREATE MEMORY TABLE "PUBLIC"."ROLE"(
    "ROLE_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_81ACF5FC_A583_4111_B0DF_39CF58406387" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_81ACF5FC_A583_4111_B0DF_39CF58406387",
    "ROLE_NOM" VARCHAR(50) NOT NULL
);
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ROLE_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.ROLE;
CREATE MEMORY TABLE "PUBLIC"."STATUT"(
    "STATUT_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_03D1C7AC_0F08_4A33_8133_E061E98C78EE" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_03D1C7AC_0F08_4A33_8133_E061E98C78EE",
    "NOM" VARCHAR(40) NOT NULL
);
ALTER TABLE "PUBLIC"."STATUT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("STATUT_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.STATUT;
CREATE MEMORY TABLE "PUBLIC"."TYPE_DON"(
    "TYPE_DON_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_EA1053B1_6576_4DB2_9D88_56F0834BDE7D" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_EA1053B1_6576_4DB2_9D88_56F0834BDE7D",
    "TYPE_DON_NOM" VARCHAR(20) NOT NULL
);
ALTER TABLE "PUBLIC"."TYPE_DON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_6" PRIMARY KEY("TYPE_DON_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TYPE_DON;
CREATE MEMORY TABLE "PUBLIC"."TYPE_PROPOSITION"(
    "TYPE_PROPOSITION_ID" BIGINT DEFAULT NEXT VALUE FOR "PUBLIC"."SYSTEM_SEQUENCE_3BFBCB41_20E8_42F4_8AF4_6FE0AA2285F2" NOT NULL NULL_TO_DEFAULT SEQUENCE "PUBLIC"."SYSTEM_SEQUENCE_3BFBCB41_20E8_42F4_8AF4_6FE0AA2285F2",
    "TYPE_PROPOSITION_LIBELLE" VARCHAR(80) NOT NULL
);
ALTER TABLE "PUBLIC"."TYPE_PROPOSITION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_D" PRIMARY KEY("TYPE_PROPOSITION_ID");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.TYPE_PROPOSITION;
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_KPNNV0IT542TQNY7B8KCVI9AP" UNIQUE("ASSOCIATION_NUMERO_RNA");
ALTER TABLE "PUBLIC"."STATUT" ADD CONSTRAINT "PUBLIC"."UK_T5V7ON4J23MYDUUDG0OQ9Y47K" UNIQUE("NOM");
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."UK_I2WXFD6PI1U0FDUCC8SUJG5CC" UNIQUE("PRESTATAIRE_EMAIL");
ALTER TABLE "PUBLIC"."ROLE" ADD CONSTRAINT "PUBLIC"."UK_9CA9PR0D3THGHL6PTUF24MR4I" UNIQUE("ROLE_NOM");
ALTER TABLE "PUBLIC"."PROPOSITION" ADD CONSTRAINT "PUBLIC"."UK_BWDEM05JIA6NIR8KKPPTVD7JV" UNIQUE("PROPOSITION_NOM");
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_BI61YIAN1LWRE9U9RLBAW4S63" UNIQUE("TELEPHONE");
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."UK_OVSOG81KXGP45HCIMA0CEV1XF" UNIQUE("MEDIA_PATH");
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_G97CMNTPAR3C7G7HE4JX4BOCE" UNIQUE("ASSOCIATION_NOM");
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."UK_A4SQRHQ65OT1A5YHTE6PRNWIR" UNIQUE("PRESTATAIRE_NOM");
ALTER TABLE "PUBLIC"."TYPE_DON" ADD CONSTRAINT "PUBLIC"."UK_LVBFI72I6QERC4MB15ORDP2PX" UNIQUE("TYPE_DON_NOM");
ALTER TABLE "PUBLIC"."CATEGORIE" ADD CONSTRAINT "PUBLIC"."UK_89Y3D23IA9RUHFHDMYA9ASPQ7" UNIQUE("NOM");
ALTER TABLE "PUBLIC"."TYPE_PROPOSITION" ADD CONSTRAINT "PUBLIC"."UK_FA8A0BBHQNCHPRTN2GBOM0S4O" UNIQUE("TYPE_PROPOSITION_LIBELLE");
ALTER TABLE "PUBLIC"."RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."UK_D2ECT9LXP1BIN909GH31BUT36" UNIQUE("RESEAU_SOCIAL_NOM");
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."UK_GKFVDTGNXH0R0VC6XDVYQU0F3" UNIQUE("ASSOCIATION_MAIL");
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."UK_LIF11UG7PQKDIMUK0BEONBFNG" UNIQUE("EMAIL");
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."UK_2RL8LT37HPH37ENRWFRGSOB0R" UNIQUE("MEDIA_URL");
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."UK_SP95J9SR511T5U5MCVK5394IX" UNIQUE("LIEN_RESEAU_SOCIAL_URL");
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."UK_ECK4NQQTR6QBB92UQYM5F0UFC" UNIQUE("PERSONNE_IDENTIFIANT");
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."UK_OTYE0TV84CJEGB5OTQ8WB65XA" UNIQUE("MEDIA_TITRE");
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."UKTDKWUFYNBMKV2RM4DQXA21L2D" UNIQUE("ASSOCIATION_ID", "PERSONNE_ID");
ALTER TABLE "PUBLIC"."CONTACT_PROFESSIONNEL" ADD CONSTRAINT "PUBLIC"."FK91VBTWFPHCIBWH2FOQ5HDD5Y8" FOREIGN KEY("CONTACT_ID") REFERENCES "PUBLIC"."PRESTATAIRE"("PRESTATAIRE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."OFFRE" ADD CONSTRAINT "PUBLIC"."FK7D2UJE6PIPXWJFXAYPIQ08WDR" FOREIGN KEY("PROPOSITION_ID") REFERENCES "PUBLIC"."PROPOSITION"("PROPOSITION_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PROPOSITION" ADD CONSTRAINT "PUBLIC"."FKQYI8P258GA7RRWSTE8OY84NOI" FOREIGN KEY("TYPE_PROPOSITION_ID") REFERENCES "PUBLIC"."TYPE_PROPOSITION"("TYPE_PROPOSITION_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."FKL90JW5NSTABN1D86OT671VDG0" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("STATUT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."CONTACT_PROFESSIONNEL" ADD CONSTRAINT "PUBLIC"."FKDTW5MY6BDYS9DBH03QJ9NOT2N" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ASSOCIATION_ID") NOCHECK;
ALTER TABLE "PUBLIC"."OFFRE" ADD CONSTRAINT "PUBLIC"."FKIWCH92SVCHHTO5WOUEDHJHBMW" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ASSOCIATION_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."FKJECJ1A4KAJ1Q22T2BDRF74GF3" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLE"("ROLE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."FK6VXV0B1D377PNHMTBD5T1MTUE" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ASSOCIATION_ID") NOCHECK;
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FK8KEPX3FVJG51KQCIR9Q9NJ4HX" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ASSOCIATION_ID") NOCHECK;
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."FKNG84MJK8470YNR5TGITGAFL5E" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ASSOCIATION_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."FK47VWC3EXI8YC0PHF8J6UPHG4D" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("STATUT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."FKRMS58XF4N4371DCJJQL25JHE5" FOREIGN KEY("CATEGORIE_ID") REFERENCES "PUBLIC"."CATEGORIE"("CATEGORIE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."FKDI7Y7UJ3OFK2FVNYCTYOINWOT" FOREIGN KEY("RESEAU_SOCIAL_ID") REFERENCES "PUBLIC"."RESEAU_SOCIAL"("RESEAU_SOCIAL_ID") NOCHECK;
ALTER TABLE "PUBLIC"."MEDIA" ADD CONSTRAINT "PUBLIC"."FK5PELR55TSIONMLT62J7SAPOJ8" FOREIGN KEY("PERSONNE_ID") REFERENCES "PUBLIC"."PERSONNE"("PERSONNE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."FKI7UAPYSGUM1TBKYWD9SL6VGFV" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("STATUT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FK7XQQSY58Y0G2JBRI4KAKJ634O" FOREIGN KEY("PERSONNE_ID") REFERENCES "PUBLIC"."PERSONNE"("PERSONNE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FK1YQLASBF9RAJ5ERY94QR9MDG7" FOREIGN KEY("TYPE_DON_ID") REFERENCES "PUBLIC"."TYPE_DON"("TYPE_DON_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ASSOCIATION" ADD CONSTRAINT "PUBLIC"."FKBQYP50TPTM2IR85AI8UEAHW7O" FOREIGN KEY("ADRESSE_ID") REFERENCES "PUBLIC"."ADRESSE"("ADRESSE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PRESTATAIRE" ADD CONSTRAINT "PUBLIC"."FKNJPH05DTGEG5OB8V0JV0VX0FH" FOREIGN KEY("ADRESSE_ID") REFERENCES "PUBLIC"."ADRESSE"("ADRESSE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."PERSONNE" ADD CONSTRAINT "PUBLIC"."FK64WYPB6GO3KIEGRP8NTDF7YWP" FOREIGN KEY("ADRESSE_ID") REFERENCES "PUBLIC"."ADRESSE"("ADRESSE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."ADHESION" ADD CONSTRAINT "PUBLIC"."FKHRDO8LX016DN1A3OT095JO964" FOREIGN KEY("PERSONNE_ID") REFERENCES "PUBLIC"."PERSONNE"("PERSONNE_ID") NOCHECK;
ALTER TABLE "PUBLIC"."DON" ADD CONSTRAINT "PUBLIC"."FKCOBXNQ6LQ8UAMG6F3PSJWEUR3" FOREIGN KEY("STATUT_ID") REFERENCES "PUBLIC"."STATUT"("STATUT_ID") NOCHECK;
ALTER TABLE "PUBLIC"."LIEN_RESEAU_SOCIAL" ADD CONSTRAINT "PUBLIC"."FKH0KBBW8UY35E2XPTHHUGA8MY7" FOREIGN KEY("ASSOCIATION_ID") REFERENCES "PUBLIC"."ASSOCIATION"("ASSOCIATION_ID") NOCHECK;